/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apsagricultura;

import apsagricultura.database.SQLConnection;
import apsagricultura.models.Planta;
import apsagricultura.utils.JTableUtils;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alvez
 */
public class FrmCadastrar extends javax.swing.JFrame {
  
  private Connection connection;
  private int updateID = -1;

  /**
   * Creates new form FrmCadastrar
   */
  public FrmCadastrar() {
    initComponents();
    desativaCampos();

    // Inicializa o objeto de conexão com o BD
    try {
      connection = SQLConnection.get();
    }
    catch(ClassNotFoundException e) {
      JOptionPane.showMessageDialog(rootPane, "A classe com.microsoft.sqlserver.jdbc.SQLServerDriver não foi encontrada. Verifique se o driver mssql-jdbc-8.4.1.jre8.jar está instalado.", "Erro", JOptionPane.ERROR_MESSAGE);
      connection = null;
    }
    catch(SQLException e) {
      JOptionPane.showMessageDialog(rootPane, "Erro de conexão com o banco de dados.", "Alerta", JOptionPane.ERROR_MESSAGE);
      connection = null;
    }
    catch(Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Erro: " + e.getLocalizedMessage(), "Alerta", JOptionPane.ERROR_MESSAGE);
      connection = null;
    }
    
    loadTablePlantas();

    this.btn_Salvar.setEnabled(false);
  }
  
  private void loadTablePlantas() {
    // Se a conexão com o banco de dados foi feita com sucesso
    if(connection != null) {
      
      // Limpa a grid
      DefaultTableModel dtm = (DefaultTableModel) this.tb_Planta.getModel();
      dtm.setRowCount(0);
      
      try {
        PreparedStatement stm = connection.prepareStatement("SELECT planta.id, planta.nome, planta.nome_cientifico, planta.dias, planta.solo FROM planta");
        ResultSet result = stm.executeQuery();

        JTableUtils.fillTable(result, this.tb_Planta);
      }
      catch(Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Erro: " + e.getMessage(), "Alerta", JOptionPane.ERROR_MESSAGE);
      }
    }
  }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txt_NomePlanta = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txt_QtdeDiasCrescimento = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    txt_Solo = new javax.swing.JTextField();
    jLabel4 = new javax.swing.JLabel();
    jLabel5 = new javax.swing.JLabel();
    txt_QtdePlantas = new javax.swing.JTextField();
    txt_NomeCientifico = new javax.swing.JTextField();
    txt_EspacamentoFileira = new javax.swing.JTextField();
    jLabel6 = new javax.swing.JLabel();
    txt_temperatura = new javax.swing.JTextField();
    jLabel7 = new javax.swing.JLabel();
    jLabel8 = new javax.swing.JLabel();
    txt_Profundidade = new javax.swing.JTextField();
    btn_Salvar = new javax.swing.JButton();
    btn_LimparTudo = new javax.swing.JButton();
    btn_Novo = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    tb_Planta = new javax.swing.JTable();
    btn_Alterar = new javax.swing.JButton();
    btn_Excluir = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);
    addFocusListener(new java.awt.event.FocusAdapter() {
      public void focusGained(java.awt.event.FocusEvent evt) {
        formFocusGained(evt);
      }
    });
    addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        formMouseClicked(evt);
      }
    });
    addWindowFocusListener(new java.awt.event.WindowFocusListener() {
      public void windowGainedFocus(java.awt.event.WindowEvent evt) {
        formWindowGainedFocus(evt);
      }
      public void windowLostFocus(java.awt.event.WindowEvent evt) {
      }
    });

    jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel1.setText("Nome da Planta");

    jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel2.setText("Nome Científico");

    jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel3.setText("Quantidade de Dias para Crescimento");

    jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel4.setText("Solo Para Plantio");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel5.setText("Quantidade de Plantas por M²");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel6.setText("Espaçamento entre as Fileiras");

    jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel7.setText("Temperatura ideal para o Solo");

    jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    jLabel8.setText("Profundidade ideal do Solo");

    btn_Salvar.setBackground(new java.awt.Color(51, 153, 0));
    btn_Salvar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btn_Salvar.setForeground(new java.awt.Color(255, 255, 255));
    btn_Salvar.setText("Salvar");
    btn_Salvar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_SalvarActionPerformed(evt);
      }
    });

    btn_LimparTudo.setBackground(new java.awt.Color(204, 0, 0));
    btn_LimparTudo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btn_LimparTudo.setForeground(new java.awt.Color(255, 255, 255));
    btn_LimparTudo.setText("Limpar Tudo");
    btn_LimparTudo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_LimparTudoActionPerformed(evt);
      }
    });

    btn_Novo.setBackground(new java.awt.Color(0, 153, 255));
    btn_Novo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btn_Novo.setForeground(new java.awt.Color(255, 255, 255));
    btn_Novo.setText("Novo");
    btn_Novo.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_NovoActionPerformed(evt);
      }
    });

    tb_Planta.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {

      },
      new String [] {
        "ID", "Nome", "Nome científico", "Tempo de germinação", "Detalhes do solo"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false, false, false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    tb_Planta.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
    jScrollPane1.setViewportView(tb_Planta);
    if (tb_Planta.getColumnModel().getColumnCount() > 0) {
      tb_Planta.getColumnModel().getColumn(3).setResizable(false);
    }

    btn_Alterar.setBackground(new java.awt.Color(0, 153, 255));
    btn_Alterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btn_Alterar.setForeground(new java.awt.Color(255, 255, 255));
    btn_Alterar.setText("Alterar");
    btn_Alterar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_AlterarActionPerformed(evt);
      }
    });

    btn_Excluir.setBackground(new java.awt.Color(204, 0, 0));
    btn_Excluir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
    btn_Excluir.setForeground(new java.awt.Color(255, 255, 255));
    btn_Excluir.setText("Excluir");
    btn_Excluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btn_ExcluirActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jLabel2)
          .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel4)
          .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jLabel1)
          .addComponent(txt_QtdeDiasCrescimento)
          .addComponent(txt_NomeCientifico)
          .addComponent(txt_NomePlanta)
          .addComponent(txt_Solo)
          .addComponent(txt_QtdePlantas)
          .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txt_EspacamentoFileira)
          .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txt_temperatura)
          .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(txt_Profundidade))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1)
          .addGroup(layout.createSequentialGroup()
            .addGap(0, 114, Short.MAX_VALUE)
            .addComponent(btn_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_Novo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_LimparTudo)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btn_Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txt_NomePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(btn_LimparTudo)
          .addComponent(btn_Novo)
          .addComponent(btn_Salvar)
          .addComponent(btn_Alterar)
          .addComponent(btn_Excluir))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_NomeCientifico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_QtdeDiasCrescimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_Solo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_QtdePlantas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel6)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_EspacamentoFileira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jLabel7)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_temperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(txt_Profundidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents
    private void desativaCampos(){
        this.txt_EspacamentoFileira.setEnabled(false);
        this.txt_NomeCientifico.setEnabled(false);
        this.txt_NomePlanta.setEnabled(false);
        this.txt_Profundidade.setEnabled(false);
        this.txt_QtdeDiasCrescimento.setEnabled(false);
        this.txt_QtdePlantas.setEnabled(false);
        this.txt_Solo.setEnabled(false);
        this.txt_temperatura.setEnabled(false);
    }
    private void ativaCampos(){
        this.txt_EspacamentoFileira.setEnabled(true);
        this.txt_NomeCientifico.setEnabled(true);
        this.txt_NomePlanta.setEnabled(true);
        this.txt_Profundidade.setEnabled(true);
        this.txt_QtdeDiasCrescimento.setEnabled(true);
        this.txt_QtdePlantas.setEnabled(true);
        this.txt_Solo.setEnabled(true);
        this.txt_temperatura.setEnabled(true);
    }
    private void btn_LimparTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LimparTudoActionPerformed
        this.txt_EspacamentoFileira.setText("");
        this.txt_NomeCientifico.setText("");
        this.txt_NomePlanta.setText("");
        this.txt_Profundidade.setText("");
        this.txt_QtdeDiasCrescimento.setText("");
        this.txt_QtdePlantas.setText("");
        this.txt_Solo.setText("");
        this.txt_temperatura.setText("");
        
        desativaCampos();
        this.btn_Salvar.setEnabled(false);
    }//GEN-LAST:event_btn_LimparTudoActionPerformed

    private void btn_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NovoActionPerformed
        ativaCampos();
    }//GEN-LAST:event_btn_NovoActionPerformed

    private void btn_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AlterarActionPerformed
      ativaCampos();
      
      this.btn_Salvar.setEnabled(true);
        
      updateID = Integer.parseInt(this.tb_Planta.getValueAt(this.tb_Planta.getSelectedRow(), 0).toString());

      try {
        PreparedStatement stmt = connection.prepareStatement("SELECT id, nome, nome_cientifico, dias, solo, densidade, espac_fileiras, temp_solo, prof_solo FROM planta WHERE planta.id = ?");
        stmt.setInt(1, updateID);
        ResultSet rs = stmt.executeQuery();
        
        Planta planta = new Planta();

        while(rs.next()) {
          planta = new Planta(
            rs.getInt("id"),
            rs.getString("nome"),
            rs.getString("nome_cientifico"),
            rs.getInt("dias"),
            rs.getString("solo"),
            rs.getFloat("densidade"),
            rs.getInt("espac_fileiras"),
            rs.getInt("temp_solo"),
            rs.getInt("prof_solo")
          );
          System.out.println(rs.getInt("temp_solo"));
        }

        txt_EspacamentoFileira.setText(Float.toString(planta.getEspacFileiras()));
        txt_NomeCientifico.setText(planta.getNomeCientifico());
        txt_NomePlanta.setText(planta.getNome());
        txt_Profundidade.setText(Integer.toString(planta.getProfSolo()));
        txt_QtdeDiasCrescimento.setText(Integer.toString(planta.getDias()));
        txt_QtdePlantas.setText(Float.toString(planta.getDensidade()));
        txt_Solo.setText(planta.getSolo());
        txt_temperatura.setText(Integer.toString(planta.getTempSolo()));
      } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Erro: " + e.getMessage(), "Alerta", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_btn_AlterarActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
       
    }//GEN-LAST:event_formWindowGainedFocus

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        
    }//GEN-LAST:event_formFocusGained

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        if(txt_EspacamentoFileira.getText().isEmpty()|| 
           txt_NomeCientifico.getText().isEmpty()||
           txt_NomePlanta.getText().isEmpty()|| 
           txt_Profundidade.getText().isEmpty()|| 
           txt_QtdeDiasCrescimento.getText().isEmpty()|| 
           txt_QtdePlantas.getText().isEmpty()||
           txt_Solo.getText().isEmpty()||
           txt_temperatura.getText().isEmpty())
        {
            this.btn_Salvar.setEnabled(false);
        }
        else{
            this.btn_Salvar.setEnabled(true);
        }
        
    }//GEN-LAST:event_formMouseClicked

    private void btn_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ExcluirActionPerformed
      int id = Integer.parseInt(this.tb_Planta.getValueAt(this.tb_Planta.getSelectedRow(), 0).toString());
      
      try {
        PreparedStatement stmt = connection.prepareStatement("DELETE FROM planta WHERE planta.id = ?");
        stmt.setInt(1, id);
        stmt.execute();
        
        loadTablePlantas();
        JOptionPane.showMessageDialog(rootPane, "A planta foi excluída com sucesso!", "Sucesso", JOptionPane.DEFAULT_OPTION);
      }
      catch(Exception e) {
        JOptionPane.showMessageDialog(rootPane, "Erro: " + e.getMessage(), "Alerta", JOptionPane.ERROR_MESSAGE);
      }
    }//GEN-LAST:event_btn_ExcluirActionPerformed

  private void btn_SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalvarActionPerformed
    try {
      String solo = this.txt_Solo.getText();
      float densidade = Float.parseFloat(this.txt_QtdePlantas.getText());
      float espacamento = Float.parseFloat(this.txt_EspacamentoFileira.getText());
      int temperatura = Integer.parseInt(this.txt_temperatura.getText());
      int profundidade = Integer.parseInt(this.txt_Profundidade.getText());
      
      Planta planta = new Planta();
      planta.setNome(this.txt_NomePlanta.getText().toUpperCase());
      planta.setNomeCientifico(this.txt_NomeCientifico.getText());
      planta.setDias(Integer.parseInt(this.txt_QtdeDiasCrescimento.getText()));
      planta.setSolo(this.txt_Solo.getText());
      planta.setDensidade(Float.parseFloat(this.txt_QtdePlantas.getText()));
      planta.setEspacFileiras(Float.parseFloat(this.txt_EspacamentoFileira.getText()));
      planta.setTempSolo(Integer.parseInt(this.txt_temperatura.getText()));
      planta.setProfSolo(Integer.parseInt(this.txt_Profundidade.getText()));
      
      PreparedStatement stmt;
      
      if(updateID == -1) {
        stmt = connection.prepareStatement("INSERT INTO planta (nome, nome_cientifico, dias, solo, densidade, espac_fileiras, temp_solo, prof_solo) " +
                                                      " VALUES (?, ?, ?, ?, ?, ?, ?, ?);");
      }
      else {
        stmt = connection.prepareStatement("UPDATE planta SET nome = ?, nome_cientifico = ?, dias = ?, solo = ?, densidade = ?, espac_fileiras = ?, temp_solo = ?, prof_solo = ? WHERE id = ?");
        stmt.setInt(9, updateID);
      }
      
      stmt.setString(1, planta.getNome());
      stmt.setString(2, planta.getNomeCientifico());
      stmt.setInt(3, planta.getDias());
      stmt.setString(4, planta.getSolo());
      stmt.setFloat(5, planta.getDensidade());
      stmt.setFloat(6, planta.getEspacFileiras());
      stmt.setInt(7, planta.getTempSolo());
      stmt.setInt(8, planta.getProfSolo());
      stmt.execute();
      
      loadTablePlantas();
      this.btn_LimparTudo.doClick();
      
      JOptionPane.showMessageDialog(rootPane, "A planta "+ planta.getNome() +" ("+ planta.getNomeCientifico() +") foi "+ (updateID == -1 ? "cadastrada" : "atualizada") +" com sucesso!", "Sucesso", JOptionPane.DEFAULT_OPTION);
      updateID = -1;
    }
    catch(Exception e) {
      JOptionPane.showMessageDialog(rootPane, "Erro: " + e.getMessage(), "Alerta", JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_btn_SalvarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastrar().setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btn_Alterar;
  private javax.swing.JButton btn_Excluir;
  private javax.swing.JButton btn_LimparTudo;
  private javax.swing.JButton btn_Novo;
  private javax.swing.JButton btn_Salvar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable tb_Planta;
  private javax.swing.JTextField txt_EspacamentoFileira;
  private javax.swing.JTextField txt_NomeCientifico;
  private javax.swing.JTextField txt_NomePlanta;
  private javax.swing.JTextField txt_Profundidade;
  private javax.swing.JTextField txt_QtdeDiasCrescimento;
  private javax.swing.JTextField txt_QtdePlantas;
  private javax.swing.JTextField txt_Solo;
  private javax.swing.JTextField txt_temperatura;
  // End of variables declaration//GEN-END:variables
}
